---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: alertmanager-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/ccma/data/alertmanager-data
  persistentVolumeReclaimPolicy: Retain
