---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pushgateway-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/ccma/data/pushgateway-data
  persistentVolumeReclaimPolicy: Retain
